# Generated by Django 5.1.3 on 2024-12-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userbalancewithdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalancewithdrawal',
            name='account_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbalancewithdrawal',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
