# Generated by Django 5.1.3 on 2024-12-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_settings_email_settings_skype'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalancewithdrawal',
            name='payment_method',
            field=models.CharField(choices=[('Paypal', 'Pending'), ('Payoneer', 'Payoneer'), ('Binance', 'Binance'), ('Bank', 'Bank'), ('Others', 'Others')], default='Paypal', max_length=10),
        ),
    ]
