# Generated by Django 5.1.3 on 2024-12-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_userbalancewithdrawal_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalancewithdrawal',
            name='payment_method',
            field=models.CharField(choices=[('Paypal', 'Paypal'), ('Payoneer', 'Payoneer'), ('Binance', 'Binance'), ('Bank', 'Bank'), ('Others', 'Others')], default='Paypal', max_length=10),
        ),
    ]
