# Generated by Django 5.1.3 on 2024-12-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_userbalancewithdrawal_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='commission',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
