# Generated by Django 5.1.3 on 2024-12-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_settings_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='notice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='commission',
            field=models.IntegerField(default=0),
        ),
    ]
