# Generated by Django 5.1.3 on 2024-12-10 15:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_settings_notice_alter_settings_commission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRevenueStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_revenue', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=15)),
                ('publisher_revenue', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=15)),
                ('admin_revenue', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=15)),
                ('total_impressions', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Admin Revenue Statistics',
                'verbose_name_plural': 'Admin Revenue Statistics',
                'ordering': ['-date'],
            },
        ),
    ]
