# Generated by Django 5.1.3 on 2024-12-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_adminrevenuestatistics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'User Management'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AlterModelOptions(
            name='userbalancewithdrawal',
            options={'ordering': ['-requested_at'], 'verbose_name': 'User Balance Withdrawal', 'verbose_name_plural': 'Withdraw Request'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Reject', 'Reject')], default='Inactive', max_length=10),
        ),
    ]
