# Generated by Django 5.1.3 on 2024-12-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_customuser_options_alter_settings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_approved',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Reject', 'Reject')], default='Inactive', max_length=10),
        ),
    ]
