# Generated by Django 5.1.3 on 2025-01-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_customgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomGroup',
        ),
    ]
