# Generated by Django 5.1.3 on 2025-01-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_customuser_address_alter_customuser_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fb_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
