# Generated by Django 5.1.3 on 2024-11-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherPlacement',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('domain_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('direct_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
