# Generated by Django 5.1.3 on 2024-11-27 20:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_statistics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('ctr', models.FloatField(default=0.0)),
                ('cpm', models.FloatField(default=0.0)),
                ('revenue', models.FloatField(default=0.0)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_statistics', to='core.publisherplacement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('placement', 'user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PlacementLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=1024)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publisherplacement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='domainplacement',
            name='domain',
        ),
        migrations.DeleteModel(
            name='Statistics',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.DeleteModel(
            name='DomainPlacement',
        ),
    ]
