# Generated by Django 5.1.3 on 2024-11-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_adstatistics_placementlink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementlink',
            name='link',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
