# Generated by Django 5.1.3 on 2024-11-29 09:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_placementlink_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherplacement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publisherplacement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='placements/images/'),
        ),
        migrations.AlterUniqueTogether(
            name='placementlink',
            unique_together={('user', 'placement')},
        ),
    ]
