# Generated by Django 5.1.3 on 2024-11-30 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_placementlink_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('proxy', models.CharField(blank=True, max_length=255, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('placement_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_logs', to='core.placementlink')),
            ],
            options={
                'unique_together': {('placement_link', 'ip_address', 'proxy', 'visited_at')},
            },
        ),
    ]
