# Generated by Django 5.1.3 on 2024-12-03 21:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_countryrevenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adstatistics',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='countryrevenue',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
