# Generated by Django 5.1.3 on 2024-12-08 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_countryrevenue_is_universal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryRevenue',
        ),
    ]
