# Generated by Django 5.1.3 on 2024-12-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_delete_countryrevenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherplacement',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
