# Generated by Django 5.1.3 on 2024-12-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adstatistics',
            name='revenue',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
