# Generated by Django 5.1.3 on 2024-12-13 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_placementlink_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adstatistics',
            options={'verbose_name_plural': 'User Statistics'},
        ),
    ]
