# Generated by Django 5.1.3 on 2025-01-21 15:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_subid_placementlink_subid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='placementlink',
            unique_together={('user', 'placement', 'subid')},
        ),
    ]
