# Generated by Django 5.1.3 on 2025-01-21 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_placementlink_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='adstatistics',
            name='subid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.subid'),
            preserve_default=False,
        ),
    ]
