# Generated by Django 5.1.3 on 2025-01-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_adstatistics_subid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subid',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='subid_icons/', verbose_name='Icon'),
        ),
    ]
