from django.core.mail import send_mail
from .models import CustomUser

def send_email(subject, message, user):
    send_mail(subject, message, 'Nixaglobal <autogenerated@nixaglobal.com>', [user.email])
